### ISSUE TITLE
plotting with default solver

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/StochasticDiffEq.jl#136]
```julia
using DifferentialEquations, DiffEqBiological, Plots
bdp = @reaction_network begin
  c₁, X --> 2X
  c₂, X --> 0
  c₃, 0 --> X
end c₁ c₂ c₃
p = (1.0,2.0,50.)
u₀ = [5.]
tspan = (0.,4.)
sprob = SDEProblem(bdp, u₀, tspan, p)
sol = solve(sprob, saveat=.004)
plot(sol, fmt=:svg)
```
gives a plot that seems to have way too few points and just uses linear interpolation:

![download](https://user-images.githubusercontent.com/9385167/54477748-efa00980-47e0-11e9-9034-fd3c8742b01a.png)

I've played around with `tstops` in the solver and `plotdensity` and neither seems to fix this issue.

**Comment by ChrisRackauckas** [comment]
Way too few points? I thought the issue was too many in the plot?

**Comment by isaacsas** [comment]
No, the issue is I can't get the plot to actually look well-resolved. Changing `tstops` to also be 1000 points doesn't seem to make a difference.

**Comment by ChrisRackauckas** [comment]
What did you set `tstops` to?

The "issue" that you're having is that the true solution hits the tolerance with only a few steps and uses linear interpolation, so it doesn't look like a small dt SDE solution, but it's still a valid path. You can constrain the dt, lower the tolerance, tstops, etc. if you want more steps, but without a stochastic interpolation (whatever that would be) it would be hard to noise the intermediate parts between steps.

**Comment by isaacsas** [comment]
```julia
sol = solve(sprob, saveat=4e-3, tstops=4e-5)
```
gives
![test](https://user-images.githubusercontent.com/9385167/54477842-13b01a80-47e2-11e9-8968-90364d3e0c72.png)

**Comment by ChrisRackauckas** [comment]
`tstops` doesn't expand scalars. You need an array if you want more than one point.

**Comment by isaacsas** [comment]
I see. I'll check that fixes it and then close if it looks good. Thanks!

**Comment by isaacsas** [comment]
Yup, I was dumb. Sorry to waste your time on that one. Thanks.

**Comment by ChrisRackauckas** [comment]
If you have ideas for high order stochastic interpolation then I'm interested though. It's a funny little problem that comes up once you're able to start solving these things efficiently!

**Comment by isaacsas** [comment]
That is an interesting issue I hadn't thought about before; since I usually just work with ODEs/PDEs and jump processes I'm not super familiar with the intermediate SDE/SPDE representations and issues that crop up there.
