### ISSUE TITLE
Properly defining multiple noise processes

### ISSUE THREAD

**Issue by WouterJRV** [JuliaDiffEq/StochasticDiffEq.jl#137]
This is partly a follow up from https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/443#issuecomment-479566916 ; and also something similar has been asked in https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/154 but the syntax seems to have changed since that one.

I am currently trying to solve a set of 3 coupled complex SDEs, they are so that the first one depends on two independent real Wiener processes, and the other two don't have explicit noise dependence.

following the documentation, I manually define real noise processes 

`function REAL_WHITE_NOISE_DIST(W,dt)
  if typeof(W.dW) <: AbstractArray
    return complex(sqrt(abs(dt))*randn(size(W.dW)))
  else
    return complex(sqrt(abs(dt))*randn(typeof(W.dW)))
  end
end` 

`function INPLACE_REAL_WHITE_NOISE_DIST(rand_vec,W,dt)
  randn!(rand_vec)
  rand_vec .*= complex(sqrt(abs(dt)))
end`

`function REAL_WHITE_NOISE_BRIDGE(W,W0,Wh,q,h)
  complex(sqrt((1-q)*q*abs(h))*randn(typeof(W.dW))+q*Wh)
end`

`function INPLACE_REAL_WHITE_NOISE_BRIDGE(rand_vec,W,W0,Wh,q,h)
 randn!(rand_vec)
  rand_vec .= complex(sqrt((1-q).*q.*abs(h)).*rand_vec.+q.*Wh)
end`

`ReWienerProcess(t0,W0,Z0=nothing) = NoiseProcess(t0,W0,Z0,REAL_WHITE_NOISE_DIST,REAL_WHITE_NOISE_BRIDGE)
ReWienerProcess!(t0,W0,Z0=nothing) = NoiseProcess(t0,W0,Z0,INPLACE_REAL_WHITE_NOISE_DIST,INPLACE_REAL_WHITE_NOISE_BRIDGE).`

furthermore, the noise_rate_prototype is given by

`A = zeros(3,2)
A[1,1] = 1
A[1,2] = 1`

And the problem becomes 

`prob=SDEProblem(f,g,u₀(0.0,10.0),p,noise_rate_prototype=complex(A),noise=ReWienerProcess!(0.0,[0.0;0.0]))
`
When I try to solve this, I get however errors:
1)with the INPLACE version: 
`MethodError: Cannot `convert` an object of type Float64 to an object of type Array{Float64,1}`

This one refers to the line randn!(rand_vec). 

2)without the INPLACE version: 
`MethodError: no method matching REAL_WHITE_NOISE_DIST(::NoiseProcess{Float64,2,Float64,Array{Float64,1},Nothing,Nothing,typeof(REAL_WHITE_NOISE_DIST),typeof(REAL_WHITE_NOISE_BRIDGE),false,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Nothing}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Nothing},false},RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus}, ::Float64, ::RandomNumbers.Xorshifts.Xoroshiro128Plus). Closest candidates are:
  REAL_WHITE_NOISE_DIST(::Any, ::Any)...` 
So it seems to me that REAL_WHITE_NOISE_DIST needs more input arguments?

There are two other minor things that I had to change with respect to the standard example of complex noise so that the problem can be properly defined in the first place

- In the definition of INPLACE_REAL_WHITE_NOISE_BRIDGE, replace (1.-q) by (1-q). I think this is the same?
- In defining ReWienerProcess(!), leave out the kwargs.

When I try to verify the results for default complex noise, I also run in trouble because DiffEqBase.wiener_randn() is not recognized.

**Comment by ChrisRackauckas** [comment]
This is supposed to be done by a matrix.

**Comment by WouterJRV** [comment]
> This is supposed to be done by a matrix.

Could you please elaborate?

**Comment by WouterJRV** [comment]
Ok, combining multiple noise processes does not seem to be the issue (except for numerical instability in my particular problem), so it has to do something with defining the real noise.
