### ISSUE TITLE
RKMil for non-square noise matrix

### ISSUE THREAD

**Issue by WouterJRV** [JuliaDiffEq/StochasticDiffEq.jl#139]
Attempting RKMilCommute for a 3x2 noise_rate_prototype gives

BoundsError: attempt to access 8×4 Array{Complex{Float64},2} at index [Base.Slice(Base.OneTo(8)), 5]
throw_boundserror(::Array{Complex{Float64},2}, ::Tuple{Base.Slice{Base.OneTo{Int64}},Int64}) at abstractarray.jl:484
checkbounds at abstractarray.jl:449 [inlined]
view at subarray.jl:147 [inlined]
perform_step!(::StochasticDiffEq.SDEIntegrator{RKMilCommute{:Ito},true,Array{Complex{Float64},1},Complex{Float64},Float64,Array{Float64,1},Float64,Float64,Complex{Float64},NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},typeof(DiffEqNoiseProcess.REAL_INPLACE_WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.REAL_INPLACE_WHITE_NOISE_BRIDGE),true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Array{Complex{Float64},1},RODESolution{Complex{Float64},2,Array{Array{Complex{Float64},1},1},Nothing,Nothing,Array{Float64,1},NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},typeof(DiffEqNoiseProcess.REAL_INPLACE_WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.REAL_INPLACE_WHITE_NOISE_BRIDGE),true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},SDEProblem{Array{Complex{Float64},1},Tuple{Float64,Float64},true,Array{Float64,1},NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},typeof(DiffEqNoiseProcess.REAL_INPLACE_WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.REAL_INPLACE_WHITE_NOISE_BRIDGE),true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},SDEFunction{true,typeof(fcoup),typeof(gcoup),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(gcoup),Nothing,Array{Complex{Float64},2}},RKMilCommute{:Ito},StochasticDiffEq.LinearInterpolationData{Array{Array{Complex{Float64},1},1},Array{Float64,1}}},StochasticDiffEq.RKMilCommuteCache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},2},Array{Float64,2}},SDEFunction{true,typeof(fcoup),typeof(gcoup),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(gcoup),StochasticDiffEq.SDEOptions{Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),CallbackSet{Tuple{},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Float64,Float64,Float64,Complex{Float64},Array{Float64,1},Float64,Array{Float64,1}},NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},typeof(DiffEqNoiseProcess.REAL_INPLACE_WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.REAL_INPLACE_WHITE_NOISE_BRIDGE),true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Complex{Float64}}, ::StochasticDiffEq.RKMilCommuteCache{Array{Complex{Float64},1},Array{Complex{Float64},1},Array{Complex{Float64},2},Array{Float64,2}}, ::Function) at low_order.jl:209
perform_step! at low_order.jl:189 [inlined]
solve!(::StochasticDiffEq.SDEIntegrator{RKMilCommute{:Ito},true,Array{Complex{Float64},1},Complex{Float64},Float64,Array{Float64,1},Float64,Float64,Complex{Float64},NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},typeof(DiffEqNoiseProcess.REAL_INPLACE_WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.REAL_INPLACE_WHITE_NOISE_BRIDGE),true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},Array{Complex{Float64},1},RODESolution{Complex{Float64},2,Array{Array{Complex{Float64},1},1},Nothing,Nothing,Array{Float64,1},NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},typeof(DiffEqNoiseProcess.REAL_INPLACE_WHITE_NOISE_DIST),typeof(DiffEqNoiseProcess.REAL_INPLACE_WHITE_NOISE_BRIDGE),true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}},true},RSWM{:RSwM3,Float64},RandomNumbers.Xorshifts.Xoroshiro128Plus},SDEProblem{Array{Complex{Float64},1},Tuple{Float64,Float64},true,Array{Float64,1},NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},typeof...

**Comment by ChrisRackauckas** [comment]
What was the example for this one?

**Comment by WouterJRV** [comment]
```
A = zeros(3,2)
A[1,1] = 1
A[1,2] = 1


function g(du,u,p,t)
    x,y,z=u
    G,U,Δ,γ=p
du[1,1]=sqrt(γ/2)*(y+z)
du[1,2]=sqrt(γ/2)*(z-y)*im
end





p=[10.0;1.0;0.0;1.0]

u₀=[complex(0.0,0.0);complex(0.0,0.0);complex(0.0,0.0)]


singlecavityprob=SDEProblem(f,g,u₀,(0.0,100.0),p,noise_rate_prototype=complex(A),noise=RealWienerProcess!(0.0,[0.0;0.0],[0.0;0.0],save_everystep=false))
```
This is simultaneously an example where sparse A has troubles, at least for time-adaptive solvers

**Comment by ChrisRackauckas** [comment]
```julia
using StochasticDiffEq
using ParameterizedFunctions
using SparseArrays

function f(du,u,p,t)
    x,y,z=u
    G,U,Δ,γ=p
    du[1]=(-0.5*γ+im*Δ)*x-im*U*(abs2(x)*x+2*x*z+conj(x)*y)-im*G*conj(x)
    du[2]=-im*U*(x^2*(1+2*z)+y*(1+4*abs2(x)+6*z))+(2*im*Δ-γ)*y-2*γ*y*z-im*G*(1+2*z)
    du[3]=2*U*imag(x^2*conj(y))-2*G*imag(y)-γ*(z+z^2+abs2(y))
end

A = zeros(3,2)
A[1,1] = 1
A[1,2] = 1

function g(du,u,p,t)
    x,y,z=u
    G,U,Δ,γ=p
    du[1,1]=sqrt(γ/2)*(y+z)
    du[1,2]=sqrt(γ/2)*(z-y)*im
end
p=[10.0;1.0;0.0;1.0]
u₀=[complex(0.0,0.0);complex(0.0,0.0);complex(0.0,0.0)]
singlecavityprob=SDEProblem(f,g,u₀,(0.0,100.0),p,noise_rate_prototype=complex(A),noise=RealWienerProcess!(0.0,[0.0;0.0],[0.0;0.0],save_everystep=false))
sol = solve(singlecavityprob,RKMilCommute())

singlecavityprob=SDEProblem(f,g,u₀,(0.0,100.0),p,noise_rate_prototype=sparse(complex(A)),noise=RealWienerProcess!(0.0,[0.0;0.0],[0.0;0.0],save_everystep=false))
sol = solve(singlecavityprob,RKMilCommute())
```

It looks like it'll fail for any non-square noise matrix, and the indexing issue is pretty subtle. I'll have to find some time to really devote to it in order to write it with linalg expressions.

**Comment by ChrisRackauckas** [comment]
The error estimator seems bad here, but 

```julia
using StochasticDiffEq, DiffEqNoiseProcess
using ParameterizedFunctions
using SparseArrays

function f(du,u,p,t)
    x,y,z=u
    G,U,Δ,γ=p
    du[1]=(-0.5*γ+im*Δ)*x-im*U*(abs2(x)*x+2*x*z+conj(x)*y)-im*G*conj(x)
    du[2]=-im*U*(x^2*(1+2*z)+y*(1+4*abs2(x)+6*z))+(2*im*Δ-γ)*y-2*γ*y*z-im*G*(1+2*z)
    du[3]=2*U*imag(x^2*conj(y))-2*G*imag(y)-γ*(z+z^2+abs2(y))
end

A = zeros(3,2)
A[1,1] = 1
A[1,2] = 1

function g(du,u,p,t)
    x,y,z=u
    G,U,Δ,γ=p
    du[1,1]=sqrt(γ/2)*(y+z)
    du[1,2]=sqrt(γ/2)*(z-y)*im
end
p=[10.0;1.0;0.0;1.0]
u₀=[complex(0.0,0.0);complex(0.0,0.0);complex(0.0,0.0)]
singlecavityprob=SDEProblem(f,g,u₀,(0.0,100.0),p,noise_rate_prototype=complex(A),noise=RealWienerProcess!(0.0,[0.0;0.0],[0.0;0.0],save_everystep=false))
sol = solve(singlecavityprob,RKMilCommute(),adaptive=false,dt=0.1)

singlecavityprob=SDEProblem(f,g,u₀,(0.0,100.0),p,noise_rate_prototype=sparse(complex(A)),noise=RealWienerProcess!(0.0,[0.0;0.0],[0.0;0.0],save_everystep=false))
sol = solve(singlecavityprob,RKMilCommute(),adaptive=false,dt=0.1)
```

Now works. Thanks @deeepeshthakur ! https://github.com/JuliaDiffEq/StochasticDiffEq.jl/pull/164
