### ISSUE TITLE
GPU compatibility of non-diagonal approximations

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/StochasticDiffEq.jl#167]
https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/master/src/caches/basic_method_caches.jl#L113-L114

These should be something like `false .* ΔW.W .* ΔW.W'`. Then the iterated integral approximations need to be done via a vectorized call instead of indexing (like this).

**Comment by deeepeshthakur** [comment]
Will get this done RN.
