### ISSUE TITLE
RKMil Stratonovich Interpretation

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/StochasticDiffEq.jl#19]
The Milstein strong order 1 derivative-free method has a Stratonovich version, which I am implementing via `RKMil(interpretation=:Stratonovich)`. However, the algorithm doesn't seem to be converging correctly right now.

Resources:
https://arxiv.org/pdf/1102.4401.pdf
https://www.doria.fi/bitstream/handle/10024/93801/new_methods.pdf?sequence=3
https://infoscience.epfl.ch/record/143450/files/sde_tutorial.pdf
http://www.sciencedirect.com/science/article/pii/S0377042706004195

For now, it won't be documented. It's commented out test is:

https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/master/test/stratonovich_convergence_tests.jl#L9

And the step is defined at:

https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/master/src/integrators/low_order.jl#L61

If anyone wants this, just take a crack at it and find out how to change that step.

**Comment by bradleyashton** [comment]
just to be clear: the Ito algorithm is converging, but Stratonovich is not?

**Comment by ChrisRackauckas** [comment]
Yes, the Ito version is converging with strong order 1. The Stratanovich version is converging with strong order 1/2.

**Comment by ChrisRackauckas** [comment]
Fixed. The problem was that only one of the predictors actually works for Stratanovich. The texts suggest using 

```julia
K = @muladd uprev .+ dt.*integrator.f(t,uprev)
utilde = @.  K + L*integrator.sqdt
```

as the derivative predictor, but `dt.*integrator.f(t,uprev)` is the Maruyama drift predictor. Instead, the prediction

```julia
utilde = @.  uprev + L*integrator.sqdt
```

gives the correct order. This actually works for both, but the first has less error and re-uses the function evaluation result in the Ito case (free!), so sticking with the old for Ito and the new for Strat
