### ISSUE TITLE
Number type tests

### ISSUE THREAD

**Issue by devmotion** [JuliaDiffEq/StochasticDiffEq.jl#190]
I'm not completely sure what the number type tests in https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/master/test/sde/sde_numbertype_tests.jl are supposed to test. At least, at some point both tests became redundant and the plotting was removed.

Can the tests be reduced to a single
```julia
solve(prob_sde_2Dlinear, SRI(), dt=1//2^(4), abstol=1, reltol=0)
```
?

**Comment by ChrisRackauckas** [comment]
Before DifferentialEquations.jl 1.0 the time type was set by dt. This has now been changed so much but the test remains and now looks absurd lol

**Comment by devmotion** [comment]
I removed the test.
