### ISSUE TITLE
RKMilCommute Adaptive error calculation

### ISSUE THREAD

**Issue by deeepeshthakur** [JuliaDiffEq/StochasticDiffEq.jl#214]
@ChrisRackauckas I think `K` is not defined in this line

https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/38f408e466e77328c48b32979733ed1711242524/src/perform_step/low_order.jl#L223

**Comment by ChrisRackauckas** [comment]
Indeed. It should be like https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/38f408e466e77328c48b32979733ed1711242524/src/perform_step/low_order.jl#L164

**Comment by deeepeshthakur** [comment]
Will make this change in the general `RKMil` I'm preparing
