### ISSUE TITLE
Calling StochasticDiffEq solvers from C

### ISSUE THREAD

**Issue by rvignolo** [JuliaDiffEq/StochasticDiffEq.jl#237]
Would it be possible to call SDEs solvers from C?

Imagine that I have both `f` and `g` functions coded in C (instead of Python or Julia itself) and I want the SDE solver to call these C functions in order to compute each step. 

Is this feasible? I imagine it is, because you already have `diffeqpy` package, which calls the SDE solver from python and functions `f` and `g` can be coded in python itself.

The other question is, would this be fast?

Thanks!

**Comment by ChrisRackauckas** [comment]
Yes. We are hoping for the ability to generate precompiled binaries for standard methods on Float64 which would make this easier (a .so), but for now you'd have to use the Julia C embedding.

https://docs.julialang.org/en/v1/manual/embedding/

It would be fast.

**Comment by rvignolo** [comment]
thanks Chris!
