### ISSUE TITLE
solution interpolation

### ISSUE THREAD

**Issue by rvignolo** [JuliaDiffEq/StochasticDiffEq.jl#251]
Hi!

I just wanted to know if it is possible to interpolate an specific simulated process, instead of all of them at a given time `t`.

I have simulated two process but I just want to get the value of one of those at a given time `t = 0.1`. Currently:
```Julia
julia> solution.u[1](0.1)
2-element Array{Float64,1}:
 0.9996913928031385
 0.01792645349537233

julia> solution.u[1](0.1)[1]
0.9996913928031385
```
In that context, I have to interpolate both processes and then get the value that I want from the resulting array. Is there any way to avoid interpolation?
```Julia
julia> solution.u[1][1](0.1)
ERROR: MethodError: objects of type Array{Float64,1} are not
callable
Use square brackets [] for indexing an Array.
Stacktrace:
 [1] top-level scope at none:0
```

Thanks!

**Comment by rvignolo** [comment]
I have checked the source code and seems it is not possible without changing it. However, it also seems that it is not that expensive. 

However, it would be nice to have a feature like that. In my problem, I use the simulations to evaluate an equation for each trajectory. For example, given two simulated processes `r` and `X`, I may have to compute an equation like the following for each trajectory:
```
max(X(T) - X(T / 2), 0) * exp(-r(T) * T)
```
This requires 3 interpolations for each trajectory: `X(T)`, `X(T/2)` and `r(T)`. However, the current StochasticDiffEq.jl implementation forces me to compute 4 interpolations (an additional interpolation for `r(T / 2)`.

Since we can have 1e5 or 1e6 trajectories, I end up computing 1e5 or 1e6 interpolations that I do not  use.

Additionally, the equations that I have to compute are far more complex than the previous one. 

Thank you very much!

**Comment by ChrisRackauckas** [comment]
`solution.u[1](0.1;idxs=1)`

**Comment by rvignolo** [comment]
I see!

**Comment by ChrisRackauckas** [comment]
No problem!
