### ISSUE TITLE
integrate stochastic solution

### ISSUE THREAD

**Issue by rvignolo** [JuliaDiffEq/StochasticDiffEq.jl#258]
Hi all!

I just wanted to know if there is a cool or easy way to integrate the solution of an SDE. 

Suppose we solve an SDEProblem and get `u(t)` as the solution. I would like to know if I can compute the integral between `[t_a, t_b]`, for arbitrary times `t_a` and `t_b`.

If there is no current implementation, what should I do:
1. Given a `t_a` point, search for the proximate left simulated value and keep it constant between `t_a` and next simulated value. Then compute rectangles between simulated values using the left value of each interval.
2. Compute an exact integral using trapezoids for each interval.

Thanks in advance!

Ramiro.

**Comment by ChrisRackauckas** [comment]
The solution `sol(t)` is a continuous function, so you can just give this to something like QuadGK.jl and it will compute an integral. Or a better method would be to just stick an extra variable in your SDE that computes the integral simultaneous to the rest of the solution.

**Comment by rvignolo** [comment]
Thanks for your reply Chris. 

Yes, I am aware that `sol(t)` is a continuous function (as an interpolated function). However, it is not smooth, so using QuadGK would not be a good approach: it could either converge slowly to the true value or not converge at all. 

So I realize I would have to integrate using the rectangle rule or the trapezoidal rule. The rectangle rule does not give the exact result while the trapezoidal does. However, I was wondering if Ito integrals are supposed to be computed using the rectangle rule, i.e. keep constant the `f_a` value for the interval `[t_a, t_b]`, for each interval.

> Or a better method would be to just stick an extra variable in your SDE that computes the integral simultaneous to the rest of the solution.

That is indeed a great approach.

**Comment by ChrisRackauckas** [comment]
Ito integrals are supposed to use the left-hand rule. But yeah, I'd just append an SDE on there and get the integral without further effort. QuadGK would work but indeed would be terrible.

**Comment by ChrisRackauckas** [comment]
I think the rule only matters when integrating with `dW`, but don't quote me on that.

**Comment by rvignolo** [comment]
Let me say thanks and a happy new year! Really useful!

**Comment by ChrisRackauckas** [comment]
Happy new year.

**Comment by rvignolo** [comment]
I was going to code this now but I have two questions that might be interesting:

I want to simulate an SDE given by only one equation `dr(t) = μ * r(t) * dt +  σ * r(t) * dW(t)`.

Is it possible that the adaptive step of the solver is reduced if I add another equation given by `dB(t) = r(t) * B(t) * dt`? 

I was wondering if a better approach would be to solve an EnsambleProblem of an ODEProblem solving the `dB(t) = r(t) * B(t) * dt` once the Stochastic solver is done.

Thanks!

**Comment by rvignolo** [comment]
Hi @ChrisRackauckas, any thoughts about my comment above?

**Comment by ChrisRackauckas** [comment]
The performance will be reduced a lot if you go from scalars to arrays, but if you go from a single scalar to a StaticArray you should be good.
