### ISSUE TITLE
SROCK Methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/StochasticDiffEq.jl#73]
- [x] SROCK2 https://hal.archives-ouvertes.fr/hal-00739754v1/document
- [x] SROCK1 https://epubs.siam.org/doi/abs/10.1137/070679375
- [x] SROCK1 Ito https://projecteuclid.org/download/pdf_1/euclid.cms/1229619673
- [x] SKSROCK https://arxiv.org/abs/1708.08145
- [x] KomBurSROCK2 https://www.sciencedirect.com/science/article/pii/S0377042712000441
- [x] TangXiaoSROCK2 https://link.springer.com/article/10.1007/s11075-018-0615-y
- [ ] SROCKC2 https://ijnao.um.ac.ir/index.php/math/article/view/69454

**Comment by ChrisRackauckas** [comment]
https://arxiv.org/abs/1708.08145

**Comment by ChrisRackauckas** [comment]
https://ijnao.um.ac.ir/index.php/math/article/view/69454

**Comment by ChrisRackauckas** [comment]
https://www.sciencedirect.com/science/article/pii/S0377042712000441

**Comment by ChrisRackauckas** [comment]
TangXiaoSROCK2 is converging with weak order 1. Could be an issue with the paper because the coefficients don't match Theorem 2's requirement.

**Comment by deeepeshthakur** [comment]
@ChrisRackauckas  I think we can close this issue now.

**Comment by ChrisRackauckas** [comment]
🎉
